### ISSUE TITLE
Add VGP view to demag_gui

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#31] opened 2016-01-21 22:23 UTC
Would be nice to have an option to view data as VGPs that comes up as a window when selected in the Tools menu of demag_gui

**Comment by Caoimhinmg** [comment] 2016-09-01 22:27
still working on adding plot interaction but I think this is more or less what you were asking for. Any suggestions?

**Comment by Swanson-Hysell** [comment] 2016-09-02 20:44
Ideally, we want to be able to view VGPs on a globe. We don't want to make Basemap a dependency for demag_gui, but if Basemap is present, it would be good to use for this purpose. Here is an example of plotting up VGPs using Basemap and ipmag.plot_vgp:

<img width="902" alt="screen shot 2016-09-02 at 1 43 50 pm" src="https://cloud.githubusercontent.com/assets/4332322/18217711/52559dd0-7113-11e6-8dcf-fdbfbc210bed.png">

**Comment by Caoimhinmg** [comment] 2016-09-06 17:25
Used basemap before, thankfully, though doing it without making that a dependency might be a trick. I'll see what I can do.

**Comment by Swanson-Hysell** [comment] 2016-09-06 17:41
Ideally, it could be an optional dependency for the program. If someone has it than the functionality is available. If they don't have it, then they get a message saying that the Basemap library is necessary for this functionality. 

I guess the decision will need to be made for the GUI whether or not to try and bundle Basemap with it.

**Comment by ltauxe** [comment] 2016-09-07 00:03
if you don’t want to add it to demag_gui, we could make it a special program under Analysis & Plots in pmag_gui  -  similar to the way it was in  MagIC.py lo these many years ago.

**Comment by Caoimhinmg** [comment] 2016-09-13 22:45
Think this feature pretty much works as intended now. I'm going to close the issue if there are any problems with the characteristics of this feature or thoughts for additions to the current form of the VGP viewer please reopen.

**Closed by Caoimhinmg** 2016-09-13 22:45 UTC
