### ISSUE TITLE
thellier_gui or pmag_gui needs to propagate required columns

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#162] opened 2017-03-16 19:44 UTC
When leaving thellier_gui.py, the specimens table does not have the required fields filled in.  also, the ages are not getting filled in from an existing ages table.   somehow this needs to be smoother for the user.   i think pmag_gui should auto propogate that info if it exists in the samples or sites table when the optional option 3 gets called.  presumably that would be the last step before creating the upload file.    I don't know if the same problem exists in demag_gui.

**Comment by moonshoes87** [comment] 2017-03-16 20:51
About the ages table:

My understanding of the ages table was that it is only for ages that were given a specific radiometric age.  Inferred ages, I though, should go in their respective tables (most likely sites) .  That was the impression I got from the discussions about ages at the MagIC meeting a while ago.  Because of that, I don’t automatically propagate any age data from specimens/samples/sites/locations into the ages table.  

Is what you want for any age data from specimens/samples/sites/locations to be all propagated into the ages table?  I can implement that if so, but it might take me a little time.

About other required fields:

I’m not sure which other fields you want to be filled in and how/when.  Can you give me some more specifics about this?  I haven’t worked much with the pmag_*.txt type data.

**Comment by ltauxe** [comment] 2017-03-16 20:58
yes that is true.  the ages use to be pulled from the er_ages.txt table to put them into the pmag_results table by specimens_results_magic so an individual investigator didn’t have to mess with it.  Ideally, the ages/locations/etc data would be in the orient.txt file that gets converted to stubs for the samples/sites tables.  not sure where we are on that little project.  anyway, perhaps pmag_gui could look if there are ages in the samples or sites tables and if not look in the ages table to propagate automatically.  I believe every site at least needs an age and right now only the age units seem to be required but not the ages.  which is weird.   

back to you :)

thanks
lisa

**Comment by moonshoes87** [comment] 2017-03-17 18:09
In the ages table, age is not a required column, because you could have instead age_high and age_low.  Age is only required *if* age_sigma is used.  age_unit is required if any columns from the Age group are present.  I am using the validations found here: https://www2.earthref.org/MagIC/data-models/3.0.   They are a bit more complicated now because there are now "Governed" columns which have specific conditional rules.

Age columns are not available in specimens or samples at all in 3.0.  In the sites and locations tables,  age columns are used, and age_unit is required.  age is a governed column, required unless age_high and age_low are used instead:

Validations:	Governed: this column must not be empty unless the age_low or age_high column is not empty.
requiredIf("age_sigma")

As far as what should be done: if I understand correctly, you want the following columns: age, age_high, age_low, age_sigma, and age_unit to propagate from sites/locations into the ages table.  In that case the information in those rows will be doubled in the contribution, showing up in both the sites table and the ages table.  I am still confused about the purpose of this...?  Either way, please confirm that the above propagation is what you want done in Pmag GUI, and I will do it.

I can also propagate age data down from sites into samples and specimens, but those columns are not legitimate in 3.0 and will be removed on upload.  

Regarding orientation magic: 

I believe orientation_magic works in 3.0, the same as it did in 2.5, but I only have one example orientation file (the one used in the Pmag GUI tutorial, and it doesn't have any age data) so the 3.0 functionality isn't very thoroughly tested at all.  If you want to send me more orientation type files, I can verify this a bit better, or you can test it if you prefer.

**Comment by moonshoes87** [comment] 2017-11-14 01:41
@ltauxe, is the propagation stuff now working as you expect?  Let me know, otherwise I will close this issue.

**Comment by njarboe** [comment] 2017-11-14 21:46
@ltauxe @moonshoes87 Is there a reason why the age table needs to be populated with the ages from locations and sites? That is, does some program read that table for ages? 

Right now we don't know how to deal with ages in detail.  Every time it is discussed we decide to think about it more. What we want is clear but hard to implement. We want every site to have an age and for there to be some way to update that age when new, better age data becomes available or for the user to decide on some alternative age model. Some major changes will have to be made for this to happen and that is in the (far?) future. 

For now I believe the age table, as you said Lori, is suppose to be for ages determined on a specific sample or site either determined in the study itself or a reference to the study that determined the age. At the site level, the data contributor just has to decide how they want to set the age (interpolation between other ages, guesstimate, same as the others near it, etc) if the site does not have an age determined by a direct method. 

Hope this helps some Lori.

**Comment by moonshoes87** [comment] 2017-11-16 21:48
Thanks, @njarboe.  

Currently, age data is not automatically propagated into the age table.  Age data is taken *from* the age table and propagated into locations/sites/samples/specimens.  Taking age data from the age table and propagating it into the other tables is useful in some cases for PmagPy plotting programs, like aniso_depthplot.

I guess the issue is this: for plotting and analysis purposes, it is helpful to have all of the ages in one place, even if they are of different qualities (study or guesstimate).  I think that it makes the most sense to do that by putting information from ages.txt into other tables (as currently implemented).  

@ltauxe, @njarboe, does this seem sensible, or should the propagation be different in some way?

**Comment by njarboe** [comment] 2017-11-17 00:57
@moonshoes87 @ltauxe This seems best. Do you fill out all of the levels from the age table when the age table is incomplete. Say the age table has two ages. One at 1 Ma for one sample and the other at 2Ma. If you had only one age you could use that for everything, but with two ages, how do you determine the age?

**Comment by moonshoes87** [comment] 2017-11-28 20:31
I'm not sure I've correctly understood your question, but here are some clarifications.

I only propagate ages using the data hierarchy. So, if site h5a has an age of 1 Ma and there are no other entries in the ages table, "1 Ma" will be propagated down only to site h5a's samples and specimens.  So:

specimen h5a10 will have the age 1 Ma
specimen h6b22 will have no value for age.

The plotting program, or whatever, that is looking for ages will then presumably use specimen h5a10 and exclude specimen h6b22 from its plot.  

If an object already has an age, it will not be overwritten (location age will not overwrite it's child sites ages).

If there are two ages for one site in ages.txt, I am not sure what should happen.  Was that the scenario you wanted me to check on?

Let me know if I've answered the question.

**Comment by moonshoes87** [comment] 2017-12-06 21:46
I'm going to close this issue for now.  If any more specific problems arise with regard to ages or other values that should propagate, let's open a new issue.

**Closed by moonshoes87** 2017-12-06 21:46 UTC
