### ISSUE TITLE
One error on the batch plots run May 20th, 2019

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#581] opened 2019-05-22 17:06 UTC
There seems to be only one Traceback error on the plots run this time.
Log is here:
http://34.236.167.37/plots/batchPlotsLog.txt
and the files are here:
http://34.236.167.37/plots/12366/

I get the same error running make_magic_plots.py on both the server and my mac, but many plots still get made.

4  records written to file  /home/magic/localPlots/tmp/12366/ages.txt
ages  data put in  /home/magic/localPlots/tmp/12366/ages.txt
-I- Using online data model
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//zeq_magic.py", line 76, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//zeq_magic.py", line 71, in main
    save_plots=save_plots, fmt=fmt, interactive=interactive, specimen=specimen)
  File "/home/magic/git/PmagPy/pmagpy/ipmag.py", line 10549, in zeq_magic
    ZED, interpretations = make_plots(s, cnt, meas_df, spec_container, samp_container)
  File "/home/magic/git/PmagPy/pmagpy/ipmag.py", line 10444, in make_plots
    ZED = pmagplotlib.plot_zed(ZED, datablock, angle, s, units)
  File "/home/magic/git/PmagPy/pmagpy/pmagplotlib.py", line 936, in plot_zed
    plot_zij(ZED['zijd'], datablock, angle, s, norm)
  File "/home/magic/git/PmagPy/pmagpy/pmagplotlib.py", line 738, in plot_zij
    tstring = s + ': NRM = ' + '%9.2e' % (datablock[0][3])
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
-I- Using online data model

**Comment by moonshoes87** [comment] 2019-05-23 04:27
Looks like this was just caused by ipmag.zeq_magic interpreting specimen names as floats instead of strings.  I'm not sure why that changed -- maybe changing the pandas version fixed one thing but broke this.

**Comment by moonshoes87** [comment] 2019-05-30 19:06
@njarboe, I got this fixed.  You can re-run plots if you want to.  I am also getting close to a new version of make_magic_plots that will create or append to an images table, and I'll let you know when we're ready to try that.

**Closed by moonshoes87** 2019-05-30 19:06 UTC
