### ISSUE TITLE
Some column names incorrect when using cit_magic.py

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#174] opened 2017-04-18 23:27 UTC
I'm not sure if this issue is in the cit_magic.py logic or the data model code but when I use cit_magic I get the following errors:

in the sample table:
geologic_class  and geologic_type should be geologic_classes and  geologic_types.
the citation column should be removed as there is also a citations column

in the specimens table: the citation column should be removed as there is also a citations column

in the measurements table:
In the 3.0 data model the measurement id column is labeled number (maybe this should be changed)
Since that is the case I think that the column "measurement" should be changed to "number" but then I am not sure what the column labeled "number" corresponds to.

**Comment by Caoimhinmg** [comment] 2017-04-19 17:18
Hey @njarboe, just pushed a change that should fix the messed up plurals. Though it should be noted that the conversion scripts don't actually check against the online data model when converting it's just a hard coded mapping. The data model is checked before upload in Pmag or Magic GUI though so it shouldn't be a problem.

As to the last thing, "measurement" is the unique index used in the underlying DataFrame representing the measurement record. It is created by new_builder when I ask it to write the table and is rather useful as it saves time when regenerating the DataFrame and provides a unique index for accessing measurement records. The "number" column is just the number of the measurement for the specimen and while in a way a duplicate of the information in "measurement" it is used in places of the GUIs which still run in 2.5 in their backend because rewriting all the GUI code would be a titanic task. So both fields are still useful from a PmagPy perspective.

**Comment by njarboe** [comment] 2017-04-19 17:49
Hi @Caoimhinmg, thanks for the quick fix. After seeing your comment, Rupert and I just talked about the current data model and made some changes. "measurement" was not a column in the 3.0 data model and the measurement id was strangely called "number". We have changed the model so that the "measurement" column is now what you described: a unique id for a measurement. The "number" column now does not exist in 3.0 (1 for the first measurement on a specimen, 2 for the second, etc.) and an already existing column called "treat_step_num" should be used for what you call "number" in the 3.0 data model.

**Comment by moonshoes87** [comment] 2017-04-19 18:03
'measurement' was initially a column that I created in new_builder.py by combining the experiment name and the number to create a unique name for each measurement.

It sounds like I should now update that code based on these changes to the data model.  To clarify:

1.  Anywhere 'number' was used, we should now use 'treat_step_num' instead.

2.  I should make a new cache of the updated data model.

3.  It sounds like I should continue automatically generating the 'measurement' column in new_builder.

Does this seem correct?

As a side note, there is a Contribution level method called remove_non_magic_cols that drops all columns that aren't in the data model.  During the normal PmagPy workflow, this is called before an upload file gets created, so any extra columns that might have been created will be dumped.  This happens a lot in PmagPy -- for example, to get a lot of the code to work as it did with 2.5, we propagate the site name down to the specimen level.  That site column then is discarded before upload.

**Comment by njarboe** [comment] 2017-04-19 18:22
@moonshoes87 That all seems correct. I am not sure if @rminnett has updated the online data model for you to grab yet, but it should be ready soon.

**Comment by rminnett** [comment] 2017-04-19 18:36
It’ll be updated later today, unless you need it right away?

**Comment by moonshoes87** [comment] 2017-04-19 19:04
No hurry.  Let me know when it’s done, and I’ll do the re-caching.

**Closed** 2017-05-02 20:06 UTC
