### ISSUE TITLE
trouble in zeq_magic.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#231] opened 2017-06-29 01:16 UTC
This doesn't work at all anymore.  i tried it on the upgraded McMurdo data set. first it complained about a missing orientation_flag in the samples table.  when that got fixed, it just quit.  no error, nothing.  
it also doesn't work on any file i can find.

**Comment by ltauxe** [comment] 2017-06-29 01:20
Here is the test file that 'should' work.  
[McMurdo.zip](https://github.com/PmagPy/PmagPy/files/1110630/McMurdo.zip)

**Comment by moonshoes87** [comment] 2017-09-20 19:37
I fixed two problems in zeq_magic.  Both were basically caused by the same type of pandas error, i.e.:
 code that checks for a column name but doesn't check to see if there is any data in that column.  So, in the McMurdo measurements the column "treat_mw_power" is present, but empty.  That means that this check:

    if 'treat_mw_power' in meas_data.columns:

causes problems, because the program then assumes that there is actual microwave data.  

Anyway, zeq_magic now seems to be working on the upgraded McMurdo data.  @ltauxe, let me know if you still have a problem here!

**Comment by moonshoes87** [comment] 2017-12-03 01:11
See MS_data

Issue with this line:

                prior_spec_data = spec_container.get_records_for_code(
                'LP-DIR', strict_match=False)  # look up all prior directional interpretations 

It is grabbing records that it shouldn't, and then breaking later.

**Comment by moonshoes87** [comment] 2017-12-04 19:29
zeq_magic is failing with a dataset that doesn't have a specimen file (or has a very minimal specimen file).  Does it need to work without saved specimen interpretations?

**Comment by ltauxe** [comment] 2017-12-04 21:50
the only thing this gets used for anymore is to make the plots for the MagIC website, so yes it should work with no saved specimen interpretations.

**Comment by ltauxe** [comment] 2017-12-04 21:53
also, even with a specimens.txt interpretation, now we get this:
-W- Column 'orientation_flag' isn't in samples table, skipping it
MS10A-1 1 out of  122
Segmentation fault: 11

so it should just assume that the orientation_flag is 'g' if there isn't one

**Comment by ltauxe** [comment] 2017-12-04 21:57
um and i think 'orientation_flag'  got changed to 'orientation_quality' and that is not an option in pmag_gui Option 3.

**Comment by ltauxe** [comment] 2017-12-04 21:59
it IS in pmag_gui - never mind.

**Comment by ltauxe** [comment] 2017-12-04 22:05
I fixed the orientation_quality flag check and there is still a segmentation fault

**Comment by moonshoes87** [comment] 2017-12-05 01:07
How do you want to assign beg_pca/end_pca when there are no saved specimen interpretations?  The current code just doesn't seem to have any way of doing this....

The two ways that beg_pcas/end_pcas are generated:

                beg_pcas = pd.to_numeric(
                    prior_specimen_interpretations.meas_step_min.values).tolist()

But this breaks if there are no previous interpretations.

This is the only other way that beg/end_pca is set in the current code:

    if '-dir' in sys.argv:
        ind = sys.argv.index('-dir')
        direction_type = sys.argv[ind + 1]
        beg_pca = int(sys.argv[ind + 2])
        end_pca = int(sys.argv[ind + 3])

**Comment by moonshoes87** [comment] 2017-12-07 05:10
I've implemented some fixes.  For one, if there are no previous interpretations zeq_magic will use all of the measurements for a specimen (this appears to be what was implemented in zeq_magic with data model 2).  I've fixed a few other miscellaneous items, too.  

Currently I'm looking at what happens with azimuth/dip information can't be found for a specimen.

**Comment by moonshoes87** [comment] 2017-12-23 02:43
@ltauxe, I now believe that zeq_magic works correctly.  I'm closing this issue, but still looking at make_magic_plots.  Let me know if you find other ways that zeq_magic doesn't work.

**Closed by moonshoes87** 2017-12-23 02:43 UTC
