### ISSUE TITLE
new bug(s) in ipmag.zeq_magic

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#578] opened 2019-05-13 12:29 UTC
**What command was run:**

ipmag.zeq_magic(meas_file='srm_dscr_measurements.txt',specimen=spc,fignum=cnt,\
                spec_file='lims_specimens.txt',input_dir_path=magic_dir,save_plots=False)

**What happened:**

first, from pmagplotlib.plot_mag(), i got this error:  
~/PmagPy/pmagpy/pmagplotlib.py in plot_mag(fignum, datablock, s, num, units, norm)
    856         plt.xlabel("Step [mT,C]")
    857     if norm == 1:
--> 858         plt.ylabel("Fractional Magnetization")
    859     if norm == 0:
    860         plt.ylabel("Magnetization")

TypeError: 'str' object is not callable

Then when I commented out the plt.ylabel() command in line 858, i got this error:  
 736     plt.xlabel(xlab)
--> 737     plt.ylabel('Circles: Y; Squares: Z')
    738     tstring = s + ': NRM = ' + '%9.2e' % (datablock[0][3])
    739     plt.axis([amin, amax, amax, amin])

TypeError: 'str' object is not callable

**What I expected to happen:**

These functions worked perfectly well as recently as yesterday.  something changed and this is such a weird bug, I can't figure it out.  I have now commented out the two ylabel commands in pmagplotlib.plot_mag and pmagplotlib.plot_zij and it works fine, except there are no ylabels.  

**Data file(s):**

[srm_dscr_measurements.txt](https://github.com/PmagPy/PmagPy/files/3172820/srm_dscr_measurements.txt)
[lims_specimens.txt](https://github.com/PmagPy/PmagPy/files/3172822/lims_specimens.txt)

**Screenshot(s):**

**PmagPy version:**
pmagpy-4.2.25-1

**Comment by moonshoes87** [comment] 2019-05-13 18:06
I'll work on this today.

**Comment by moonshoes87** [comment] 2019-05-13 18:56
I can't reproduce this.  I did find a different bug that was happening because I didn't have a samples file, and I fixed that.

When I added y-labels back in and ran:

`ipmag.zeq_magic(meas_file='srm_dscr_measurements.txt',n_plots="all", 
                spec_file='lims_specimens.txt',save_plots=False)`

all plots were made with y axis labels.

![image](https://user-images.githubusercontent.com/1836578/57645996-71f44200-7574-11e9-8a99-a22acd498386.png)

I wonder if this is a matplotlib version issue?  Could you have updated recently?

This is what I have for matplotlib version:

```
conda list | grep "matplotlib"
matplotlib                2.2.3            py36h54f8f79_0 
```

Hmmm, I just tried running it with matplotlib 3.0.3, and I still can't get your error.  Do you have some un-committed local changes?  If you stash those, does the error go away?

**Comment by moonshoes87** [comment] 2019-05-23 04:33
@ltauxe, let me know when you have another chance to try this out.  It still works fine for me, and I'd like to put those y-labels back in on master.

**Closed** 2019-05-29 22:46 UTC
Labels: Bug - Affects Features
