### ISSUE TITLE
Pmag GUI--Reopening misaligned bad measurements

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy#485] opened 2018-12-08 23:39 UTC
Using the DemagGui within the PmagGui 4.2.5 Standalone for Windows, we encountered an error.  Measurements that were marked bad on a previous opening of site/sample file shifted up down one measurement (irregardless of temperature step.)  This happened in multiple different site files.  This is on a Windows 64x bit laptop using Windows 10 Home v. 1803.

**Comment by moonshoes87** [comment] 2018-12-10 21:05
@sslotznick, I can't reproduce this error yet.  Can you please specify the exact steps you took?  (E.g., opened Demag GUI, marked measurements as bad, saved tables, closed Demag GUI).  I'm not sure I understand exactly what you mean by "opening" site/sample files.

Also, it might help if you could send me an example files of before and after.

Thanks for reporting this bug!

**Comment by sslotznick** [comment] 2018-12-11 01:49
@moonshoes87, I have attached screenshots of what steps were taken.  Essentially it is as you said, we would opened Demag GUI, mark measurements as bad, save tables, and then close Demag GUI.  Then when we reopened Demag GUI the error would occur.  

This happened with PmagGui 4.2.5 Standalone and a similar issue on 3.18.0.  

[ErrorSteps.pdf](https://github.com/PmagPy/PmagPy/files/2665616/ErrorSteps.pdf)

**Comment by moonshoes87** [comment] 2018-12-12 21:15
Thank you for the detailed bug report.  I’m able to reproduce the issue now, and I’ll let you know when I have a solution!

**Comment by moonshoes87** [comment] 2018-12-14 19:18
@sslotznick, I have a fix on the master branch.  I will make new releases for pip and standalones today or on Monday, then I will close this issue.

**Comment by moonshoes87** [comment] 2018-12-18 00:36
@sslotznick, sorry for the delay!  I'm fixing some more edge cases, and will release very soon.

**Comment by moonshoes87** [comment] 2019-01-01 20:18
@sslotznick, this should be entirely fixed in all releases.

**Closed by moonshoes87** 2019-01-01 20:18 UTC
