### ISSUE TITLE
prevent phantom sample/sites in thellier_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#355] opened 2018-05-27 01:08 UTC
When someone re-assigns specimens to samples to different site names, for example in Pmag GUI,  if one has already looked at the data in thellier_gui, there are phantom sample/site tables in the measurements table that thellier_gui will keep using, despite the update.   this is unexpected behavior.  i don't think we should write out the sample/site info into the measurements table.

**Comment by moonshoes87** [comment] 2018-05-28 23:29
This should be simple to fix.  The reason it is like that is because Thellier GUI does need sample/site data linked to measurements, so those data are propagated down.  The reason they were being saved is because the propagation takes time, so I would just leave those columns in place in the measurement table and then remove the unneeded columns during the upload step.  However, you are right that this causes problems if samples and sites are reassigned.

**Comment by moonshoes87** [comment] 2018-05-29 21:53
Lisa, I thought I knew what was going on but I actually can't reproduce this problem.  Sorry not to be able to sleuth it out, but can you send me the data_files and the steps you took to get the problem?

**Closed** 2018-09-06 19:29 UTC
Labels: Bug - Affects Features
