### ISSUE TITLE
When saving MagIC tables in demag_gui the sites table is overwritten and only sites that have interpreted specimens get saved

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#187] opened 2017-05-03 17:38 UTC
In the current master branch (probably the same on Python 2 as well). When I interpreted specimens BL8129A-BL8136A fitting 200-800mT for each (these high levels are due to USGS using Oe instead of mT which needs to be fixed probably with another option in cit_magic) and create a site mean using a Fisher fit and then "Save MagIC Tables", the original sites.txt table is replaced with one that has only the one site that has a direction calculated by demag_gui. The terminal text while running pmag_gui is below.
  
MagIC files before running pmag_gui/demag_gui:
[OrgMagICFiles.zip](https://github.com/PmagPy/PmagPy/files/974191/OrgMagICFiles.zip)

MagIC files after running pmag_gui/demag_gui:
[PostMagICFiles.zip](https://github.com/PmagPy/PmagPy/files/974192/PostMagICFiles.zip)

I'm not sure the best way to tackle this problem.

kamacite:MagICTables njarboe$ pmag_gui.py
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
-I- Fetching output frame
-I- Fetching output frame
-I- Read in any available data from working directory
-I- Using cached 3.0 data model
-I- Using cached method codes
-I- Using cached vocabularies
-I- Importing suggested vocabularies from https://earthref.org
-I- Using cached suggested vocabularies
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/contribution.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/criteria.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/ages.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/images.txt
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/criteria.txt
-I- can't find zeq_gui_preferences file, using defualt default
data model: 3.0
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/criteria.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/ages.txt
sample already in specimens
-I- done sorting meas data
/Users/njarboe/anaconda/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
No lower bound for Fit 1 on specimen BL8129A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8129A using last step (800.0mT) for upper bound
No lower bound for Fit 1 on specimen BL8130A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8130A using last step (800.0mT) for upper bound
No lower bound for Fit 1 on specimen BL8131A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8131A using last step (800.0mT) for upper bound
No lower bound for Fit 1 on specimen BL8132A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8132A using last step (800.0mT) for upper bound
No lower bound for Fit 1 on specimen BL8133A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8133A using last step (800.0mT) for upper bound
No lower bound for Fit 1 on specimen BL8134A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8134A using last step (800.0mT) for upper bound
No lower bound for Fit 1 on specimen BL8135A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8135A using last step (800.0mT) for upper bound
No lower bound for Fit 1 on specimen BL8136A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8136A using last step (800.0mT) for upper bound
no PCA type found setting to line
no PCA type found setting to line
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/specimens.txt
-I- writing ages data to /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/ages.txt
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/sites.txt
no PCA type found setting to line
no measurement data found loaded for specimen current_BL8129A and will be ignored
Log file was never openned it cannot be closed
-I- Read in any available data from working directory
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/contribution.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/criteria.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/images.txt
kamacite:MagICTables njarboe$ pmag_gui.py

**Comment by Caoimhinmg** [comment] 2017-05-03 23:02
This was a serious one @njarboe, I've tried squashing this about two dozen times at this point I think ever since we switched to data model 3. Think I've finally cracked it though, give it another shot. Part of it was just a lot of little things caused by Python3, part of it was me over complicating things. This new method seems more stable than the old one and worked like a charm over here. Let me know if you get any weird behaviour. If everything seems good on your end feel free to close the issue.

**Comment by njarboe** [comment] 2017-05-05 21:21
@Caoimhinmg, I tried running today's pull of pmag_gui.py (I'm trying to use only Python 3 versions of programs so that we can get to 3 as soon as possible, so I mean Python 3 unless otherwise stated) on Hagstum's data files. 
[OrgHagstrumFiles.zip](https://github.com/PmagPy/PmagPy/files/980331/OrgHagstrumFiles.zip)
And then fit all of the specimens of site BL8192 using 200-800. Then when I tried to save the Magic Tables I got an error. Console output below. Here are the after files when I Ctrl-C'd out.
[AfterHagstrumFiles.zip](https://github.com/PmagPy/PmagPy/files/980346/AfterHagstrumFiles.zip)
On reopening pmag_gui it looks like the specimen fits are there but not the site means.
If you can take a look, that would be great.

kamacite:test njarboe$ pmag_gui.py
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
-I- Fetching output frame
-I- Fetching output frame
-I- Read in any available data from working directory
-I- Using cached 3.0 data model
-I- Using cached method codes
-I- Using cached vocabularies
-I- Importing suggested vocabularies from https://earthref.org
-I- Using cached suggested vocabularies
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/contribution.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/criteria.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/ages.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/images.txt
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/criteria.txt
-I- can't find zeq_gui_preferences file, using defualt default
data model: 3.0
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/criteria.txt
-W- No such file: /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/ages.txt
sample already in specimens
-I- done sorting meas data
/Users/njarboe/anaconda/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
No lower bound for Fit 1 on specimen BL8129A using lowest step (0) for lower bound
No upper bound for fit Fit 1 on specimen BL8129A using last step (800.0mT) for upper bound
-I- overwriting /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/specimens.txt
-I- writing ages data to /Users/njarboe/Dropbox/MagIC/people/Hagstrum/BORING/uploadFiles/MagICTables/test/ages.txt
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 5778, in on_menu_make_MagIC_results_tables
    self.On_close_MagIC_dialog(dia)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 4547, in On_close_MagIC_dialog
    locations = sorted(list(spec_df['location'].drop_duplicates()))
TypeError: '<' not supported between instances of 'str' and 'float'

^C

**Comment by moonshoes87** [comment] 2017-05-05 21:29
It looks like we might just need to drop null values here, because they are breaking the sorting.  This is an easy fix assuming that it is “ok” that for the specimens.location column to have null values at this point in the workflow…  But if the presence of null values in this column is a problem, then there is a deeper issue to fix.

**Comment by njarboe** [comment] 2017-05-05 21:41
@moonshoes87 @Caoimhinmg I think it is OK to require that specimens must have parents up to location and the same for samples and sites and measurements. I did not realize that this was the problem. I thought the problem was that some sites had measurements/specimens/samples and some sites had no children. Hagstrum's data all have parents and it is the cit_magic program that needs to be modified to get all the tables correct. I can look into modifying cit_magic next week to put in the needed columns unless @Caoimhinmg has time today or over the weekend. I think null values or adding a dummy 'unknown' place holder is not the best and instead print a descriptive error informing the user to correct their data by adding the location or other info needed. Maybe suggest the user add a placeholder name that can be changed in the future, but most scientist will figure that out. I hope this clears things up a bit.

**Comment by njarboe** [comment] 2017-05-06 06:09
I closed this on accident. Now reopened

**Comment by moonshoes87** [comment] 2017-05-16 06:04
@njarboe, I just pushed a fix for this (basically reverting to @Caoimhinmg's original way of doing it, plus adding a warning that some measurements are being deleted).  With the data from OrgMagICFiles.zip, this means that 1747 measurements are excluded for lack of a location name.  There is only one site in the sites table, so there is only one available site --> location relationship.

However, I'm guessing that what you *really* want is not just a warning that says "you are missing this many locations at the measurement level, so we are excluding these measurements".  You really want a warning that says, (in this particular case), "of the 41 sites you reference in the sample table, only 1 is present in the sites table".  That way the user actually knows where data are missing and can fill them in accordingly.

Am I correct that this is the behavior you would ideally like?  It is a little bit tricky to implement this robustly, but I am guessing it would be useful.

**Comment by moonshoes87** [comment] 2017-05-24 18:25
From discussions with @njarboe:

Make the warning a pop-up so it is harder to miss.  Warning something like:  This many measurements cannot be associated with a location.  Try using Pmag GUI step 3 to make sure you have the full chain from specimens --> locations.

We may want to implement a more informative error message later, but this is not a top priority.

**Comment by moonshoes87** [comment] 2017-06-08 20:07
@njarboe, are you satisfied with the current behavior of Demag GUI on this issue?  If so, feel free to close it, or I can.

**Closed** 2017-11-14 01:43 UTC
Labels: Bug - Affects Features
